
spring:
  datasource:
    url: jdbc:h2:file:./bank_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  hateoas:
    use-hal-as-default-json-media-type: false

server:
  port: 8889
  servlet:
    context-path: /api/v1

error-messages:
  bankNotExists: Банка с id:{0} не существует
  clientExists: Клиент с именем {0} уже зарегистрирован в банке
  clientNotFound: Клиент с именем {0} не найден
  inBankNotFoundClients: В банке с id:{0} нет клиентов
  notEnoughFunds: Не удалось снять со счета {0} {1} рублей тaк как недостаточно средств
  accountNotFound: Счет с номером {0} не найден