POST {{client_api}}
Accept: application/json
Content-Type: application/json

{
"name": "Brad Super _"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###

GET {{client_api}}/all-names
Accept: application/json
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###